version: '3.7'

services:
  postgres:
    image: 'postgres:${POSTGRES_VERSION}'
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ./config.env

  redis:
    image: 'redis:${REDIS_VERSION}'
    restart: always
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - redis-data:/data
    env_file:
      - ./config.env

volumes:
  postgres-data:
  redis-data
