# To run this docker compose use "docker compose --env-file ./config.env up -d"

version: '3.7'
services:
  postgres:
    image: postgres:${POSTGRES_VERSION}
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  redis:
    image: redis:${REDIS_VERSION}
    restart: always
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:

